### ISSUE TITLE
Making sure we get our marks for the course

### ISSUE THREAD

**Issue by chris-dare** [bobweeman/blog#2]
Hi, class. In case you're finding it difficult setting up this project successfully in your development environment kindly follow these steps. I hope you'll find them helpful:

Steps to getting marks for the laravel blog project

1. Go to https://github.com/bobweeman/blog
2. Fork the repository. For simplicity call your repository "blog"
3. Clone your new repository that you have forked
4. Enter the repository folder. 
5. In the folder, rename the .env.example file to .env
6. Go to localhost/phpmyadmin or mysql console and create a new database. 
For simplicity, call it larablog
7. Go back to your .env
8. In your .env file, change the value of the "DB_DATABASE" property to the name of the database you just created
9. Also in your .env file, change the value of the "DB_USERNAME" from "homestead" to your database username
10. Also in your .env file, change the value of the "DB_PASSWORD" from "secret" to the corresponding password for the database username you entered in step 9
11. Open your laravel project folder in the terminal/command line and type "php artisan key:generate" to generate your application key
12. Also, run the command "php artisan migrate"
13. Now run the command "php artisan serve" and head to your application at the specified url in your browser. 
14. There is no step 14. You're done.

**Comment by chris-dare** [comment]
Mr. Asamoa, personally I'm also a bit lost on how far we've come so far. Please is it possible for you to post a list of the parts of the framework we have learned so far so we know what to revise? Also it may be helpful to add the list of future topics so you can point us in the right direction. Thank you.

**Comment by developernanayaa** [comment]
laravel,laravel,laravel 
it is well
hmmmmmmmmmmmmmmmmmmmmmmm

**Comment by developernanayaa** [comment]
errors upon errors 
oooooops it looks like something went wrong ......
Mr Asamoah come to my rescue oooooooo
else i will soon jump from baobab room 6 to the grand floor

**Comment by chris-dare** [comment]
Looooool
